[versions]
kotlin = "2.3.0"
agp = "8.13.0"
androidx-core = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-fragment = "1.8.9"
androidx-activity = "1.12.4"
androidx-constraintlayout = "2.2.1"
cicerone = "7.1"
kctfork = "0.12.1"
junit5 = "6.0.3"
compileSdk = "36"
minSdk = "24"
targetSdk = "35"
vbpd = "2.0.4"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
cicerone = { module = "com.github.terrakok:cicerone", version.ref = "cicerone" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

vbpd = { module = "dev.androidbroadcast.vbpd:vbpd", version.ref = "vbpd" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
screen = { id = "com.adkhambek.screen" }
viewbinding = { id = "com.adkhambek.viewbinding" }
